

default: &default
  adapter: mysql2
  encoding: utf8
  timeout: 5000
  username: root
  password: root

development:
  <<: *default
  database: mydb

test:
  <<: *default
  database: mydb

production:
  <<: *default
  database: mydb
